tasks:
  - name: open a terminal
    openMode: tab-after
  - name: show markdown readme
    command: sleep 5 && open README.md
    openMode: tab-before
    
ports:
  - port: 8000
    onOpen: open-preview
